/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stream/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stream Reset */
    post: operations["stream_reset_api_stream_reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stream/advance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stream Advance */
    post: operations["stream_advance_api_stream_advance_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stream/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream State */
    get: operations["stream_state_api_stream_state_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Overview */
    get: operations["overview_api_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/detections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detections */
    get: operations["detections_api_detections_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/detections/{detection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detection Detail */
    get: operations["detection_detail_api_detections__detection_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/source-capability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Source Capability */
    get: operations["source_capability_api_source_capability_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Event Detail */
    get: operations["event_detail_api_events__event_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Action */
    Action: {
      /** Source */
      source: string;
      /** Verb */
      verb: string;
      /** Category */
      category: string;
    };
    /** Detection */
    Detection: {
      /** Detection Id */
      detection_id: string;
      /** Scenario */
      scenario: string;
      /** Title */
      title: string;
      /** Score */
      score: number;
      /** Confidence */
      confidence: number;
      /** Severity */
      severity: string;
      /** Reasons */
      reasons: string[];
      /** Feature Attributions */
      feature_attributions: {
        [key: string]: number;
      };
      /** Event Ids */
      event_ids: string[];
      /** Related Entity Ids */
      related_entity_ids: string[];
      /** Evidence */
      evidence: components["schemas"]["EvidencePointer"][];
      /** Model Version */
      model_version: string;
      /** Status */
      status: string;
    };
    /** DetectionDetail */
    DetectionDetail: {
      detection: components["schemas"]["Detection"];
      peer_comparison: components["schemas"]["DetectionPeerComparison"];
      evidence_bundle: components["schemas"]["DetectionEvidenceBundle"];
      /** Events */
      events: components["schemas"]["Event"][];
    };
    /** DetectionEvidenceBundle */
    DetectionEvidenceBundle: {
      /** Evidence Items */
      evidence_items: components["schemas"]["EvidenceBundleItem"][];
    };
    /** DetectionList */
    DetectionList: {
      /** Items */
      items: components["schemas"]["Detection"][];
      page: components["schemas"]["Pagination"];
    };
    /** DetectionPeerComparison */
    DetectionPeerComparison: {
      /** Principal Id */
      principal_id: string;
      /** Peer Group */
      peer_group: string;
      /** Resource Id */
      resource_id: string;
      /** Principal Total Events */
      principal_total_events: number;
      /** Principal Prior Resource Access Count */
      principal_prior_resource_access_count: number;
      /** Peer Group Resource Access Count */
      peer_group_resource_access_count: number;
      /** Peer Group Principal Count */
      peer_group_principal_count: number;
      /** Detection Reasons */
      detection_reasons: string[];
    };
    /** Event */
    Event: {
      /** Event Id */
      event_id: string;
      /** Source */
      source: string;
      /** Source Event Id */
      source_event_id: string;
      principal: components["schemas"]["Principal"];
      resource: components["schemas"]["Resource"];
      action: components["schemas"]["Action"];
      /** Observed At */
      observed_at: string;
      /** Environment */
      environment: {
        [key: string]: unknown;
      };
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
      evidence: components["schemas"]["EvidencePointer"];
    };
    /** EventList */
    EventList: {
      /** Items */
      items: components["schemas"]["Event"][];
      page: components["schemas"]["Pagination"];
    };
    /** EvidenceBundleItem */
    EvidenceBundleItem: {
      pointer: components["schemas"]["EvidencePointer"];
      /** Raw Payload */
      raw_payload: {
        [key: string]: unknown;
      } | null;
      /** Retention Expired */
      retention_expired: boolean;
    };
    /** EvidencePointer */
    EvidencePointer: {
      /** Source */
      source: string;
      /** Object Key */
      object_key: string;
      /** Raw Event Id */
      raw_event_id: string;
      /** Observed At */
      observed_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /** OpsMetadata */
    OpsMetadata: {
      /** Workspace */
      workspace?: string | null;
      /** Event Counts By Source */
      event_counts_by_source: {
        [key: string]: number;
      };
      /** Dead Letter Count */
      dead_letter_count: number;
      /** Dead Letter Counts By Source */
      dead_letter_counts_by_source?: {
        [key: string]: number;
      } | null;
      /** Contains Raw Payloads */
      contains_raw_payloads?: boolean | null;
    };
    /** Overview */
    Overview: {
      stream_state: components["schemas"]["StreamState"];
      ops_metadata: components["schemas"]["OpsMetadata"];
    };
    /** Pagination */
    Pagination: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
      /** Has More */
      has_more: boolean;
    };
    /** Principal */
    Principal: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Provider */
      provider: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Department */
      department: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
    };
    /** Resource */
    Resource: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Provider */
      provider: string;
      /** Name */
      name: string;
      /** Sensitivity */
      sensitivity: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
    };
    /** SourceCapabilityDetails */
    SourceCapabilityDetails: {
      /** Display Name */
      display_name: string;
      /** Required Event Types */
      required_event_types: string[];
      /** Required Fields */
      required_fields: string[];
      /** Seen Event Types */
      seen_event_types: string[];
      /** Missing Required Event Types */
      missing_required_event_types: string[];
      /** Required Field Coverage */
      required_field_coverage: {
        [key: string]: boolean;
      };
      /** Missing Required Fields */
      missing_required_fields: string[];
      /** Raw Event Count */
      raw_event_count: number;
      /** Normalized Event Count */
      normalized_event_count: number;
      /** Dead Letter Count */
      dead_letter_count: number;
      /** Dead Letter Reason Counts */
      dead_letter_reason_counts: {
        [key: string]: number;
      };
    };
    /** SourceCapabilityMatrix */
    SourceCapabilityMatrix: {
      /** Source Pack */
      source_pack: string[];
      /** Sources */
      sources: {
        [key: string]: components["schemas"]["SourceCapabilityDetails"];
      };
    };
    /** StreamAdvance */
    StreamAdvance: {
      /** Status */
      status: string;
      /** Cursor */
      cursor: number;
      /** Total Source Events */
      total_source_events: number;
      /** Complete */
      complete: boolean;
      /** Batch Size */
      batch_size: number;
      /** Ingest */
      ingest: {
        [key: string]: unknown;
      };
      /** Detect */
      detect: {
        [key: string]: unknown;
      };
      ops_metadata: components["schemas"]["OpsMetadata"];
    };
    /** StreamReset */
    StreamReset: {
      /** Status */
      status: string;
      /** Total Source Events */
      total_source_events: number;
      /** Cursor */
      cursor: number;
    };
    /** StreamState */
    StreamState: {
      /** Cursor */
      cursor: number;
      /** Total Source Events */
      total_source_events: number;
      /** Complete */
      complete: boolean;
      /** Normalized Event Count */
      normalized_event_count?: number | null;
      /** Detection Count */
      detection_count?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  stream_reset_api_stream_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamReset"];
        };
      };
    };
  };
  stream_advance_api_stream_advance_post: {
    parameters: {
      query?: {
        batch_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamAdvance"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_state_api_stream_state_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamState"];
        };
      };
    };
  };
  overview_api_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Overview"];
        };
      };
    };
  };
  events_api_events_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detections_api_detections_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectionList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detection_detail_api_detections__detection_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        detection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectionDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  source_capability_api_source_capability_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceCapabilityMatrix"];
        };
      };
    };
  };
  event_detail_api_events__event_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
