/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/intake/raw-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Intake Raw Events */
    post: operations["intake_raw_events_api_intake_raw_events_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workers/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Worker State */
    get: operations["worker_state_api_workers_state_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runtime-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runtime Status */
    get: operations["runtime_status_api_runtime_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stream/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stream Reset */
    post: operations["stream_reset_api_stream_reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stream/advance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stream Advance */
    post: operations["stream_advance_api_stream_advance_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stream/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream State */
    get: operations["stream_state_api_stream_state_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Overview */
    get: operations["overview_api_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/detections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detections */
    get: operations["detections_api_detections_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/detections/{detection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detection Detail */
    get: operations["detection_detail_api_detections__detection_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/entities/{principal_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Entity Detail */
    get: operations["entity_detail_api_entities__principal_key__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/detections/{detection_id}/acknowledge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Detection Acknowledge */
    post: operations["detection_acknowledge_api_detections__detection_id__acknowledge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/source-capability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Source Capability */
    get: operations["source_capability_api_source_capability_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Event Detail */
    get: operations["event_detail_api_events__event_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Action */
    Action: {
      /** Source */
      source: string;
      /** Verb */
      verb: string;
      /** Category */
      category: string;
    };
    /** CanonicalEventStoreStatus */
    CanonicalEventStoreStatus: {
      /** Canonical Store */
      canonical_store: string;
      /** Canonical Format */
      canonical_format: string;
      /** Query Backend */
      query_backend: string;
      /** Detail Hydration */
      detail_hydration: string;
      /** Cursor Query Support */
      cursor_query_support: boolean;
      /** Text Query Support */
      text_query_support: boolean;
      /** Time Range Support */
      time_range_support: boolean;
    };
    /** Detection */
    Detection: {
      /** Detection Id */
      detection_id: string;
      /** Scenario */
      scenario: string;
      /** Title */
      title: string;
      /** Score */
      score: number;
      /** Confidence */
      confidence: number;
      /** Severity */
      severity: string;
      /** Reasons */
      reasons: string[];
      /** Feature Attributions */
      feature_attributions: {
        [key: string]: number;
      };
      /** Event Ids */
      event_ids: string[];
      /** Related Entity Ids */
      related_entity_ids: string[];
      /** Evidence */
      evidence: components["schemas"]["EvidencePointer"][];
      /** Model Version */
      model_version: string;
      model_rationale?: components["schemas"]["DetectionModelRationale"] | null;
      /** Status */
      status: string;
    };
    /** DetectionContextStatus */
    DetectionContextStatus: {
      /** Available */
      available: boolean;
      /** Event Count */
      event_count: number;
      /** Input Signature */
      input_signature?: string | null;
      /** Context Version */
      context_version: number;
    };
    /** DetectionDetail */
    DetectionDetail: {
      detection: components["schemas"]["Detection"];
      peer_comparison: components["schemas"]["DetectionPeerComparison"];
      evidence_bundle: components["schemas"]["DetectionEvidenceBundle"];
      /** Events */
      events: components["schemas"]["Event"][];
    };
    /** DetectionEvidenceBundle */
    DetectionEvidenceBundle: {
      /** Evidence Items */
      evidence_items: components["schemas"]["EvidenceBundleItem"][];
    };
    /** DetectionList */
    DetectionList: {
      /** Items */
      items: components["schemas"]["Detection"][];
      page: components["schemas"]["Pagination"];
    };
    /** DetectionModelRationale */
    DetectionModelRationale: {
      /** Scoring Mode */
      scoring_mode: string;
      /** Policy Scope */
      policy_scope: string;
      /** Detection Threshold */
      detection_threshold: number;
      /** High Severity Threshold */
      high_severity_threshold: number;
      /** Model Score */
      model_score: number;
      /** Score Margin */
      score_margin: number;
      /** Calibration Source */
      calibration_source?: string | null;
      /** Calibration Reason */
      calibration_reason?: string | null;
    };
    /** DetectionPeerComparison */
    DetectionPeerComparison: {
      /** Principal Id */
      principal_id: string;
      /** Peer Group */
      peer_group: string;
      /** Resource Id */
      resource_id: string;
      /** Principal Role */
      principal_role: string;
      /** Principal Location */
      principal_location: string;
      /** Principal Privilege Level */
      principal_privilege_level: string;
      /** Principal Total Events */
      principal_total_events: number;
      /** Principal Prior Event Count */
      principal_prior_event_count: number;
      /** Principal Prior Action Count */
      principal_prior_action_count: number;
      /** Principal Prior Resource Access Count */
      principal_prior_resource_access_count: number;
      /** Peer Group Resource Access Count */
      peer_group_resource_access_count: number;
      /** Peer Group Principal Count */
      peer_group_principal_count: number;
      /** Peer Group Resource Principal Count */
      peer_group_resource_principal_count: number;
      /** Department Peer Count */
      department_peer_count: number;
      /** Manager Peer Count */
      manager_peer_count: number;
      /** Group Peer Count */
      group_peer_count: number;
      /** Geo Seen Before */
      geo_seen_before: boolean;
      /** Detection Reasons */
      detection_reasons: string[];
    };
    /** EntityDetail */
    EntityDetail: {
      principal: components["schemas"]["Principal"];
      overview: components["schemas"]["EntityOverview"];
      peer_comparison: components["schemas"]["DetectionPeerComparison"];
      /** Timeline */
      timeline: components["schemas"]["Event"][];
    };
    /** EntityOverview */
    EntityOverview: {
      /** Latest Observed At */
      latest_observed_at?: string | null;
      /** First Observed At */
      first_observed_at?: string | null;
      /** Timeline Event Count */
      timeline_event_count: number;
      /** Total Event Count */
      total_event_count: number;
      /** Distinct Source Count */
      distinct_source_count: number;
      /** Distinct Sources */
      distinct_sources: string[];
      /** Distinct Resource Count */
      distinct_resource_count: number;
      /** High Sensitivity Event Count */
      high_sensitivity_event_count: number;
    };
    /** Event */
    Event: {
      /** Event Id */
      event_id: string;
      /** Event Key */
      event_key: string;
      /** Integration Id */
      integration_id?: string | null;
      /** Source */
      source: string;
      /** Source Event Id */
      source_event_id: string;
      principal: components["schemas"]["Principal"];
      resource: components["schemas"]["Resource"];
      action: components["schemas"]["Action"];
      /** Observed At */
      observed_at: string;
      /** Environment */
      environment: {
        [key: string]: unknown;
      };
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
      evidence: components["schemas"]["EvidencePointer"];
    };
    /** EventIndexStatus */
    EventIndexStatus: {
      /** Available */
      available: boolean;
      /** Event Count */
      event_count: number;
      /** Principal Key Count */
      principal_key_count: number;
      /** Resource Key Count */
      resource_key_count: number;
      /** Department Count */
      department_count: number;
      /** Input Signature */
      input_signature?: string | null;
    };
    /** EventList */
    EventList: {
      /** Items */
      items: components["schemas"]["Event"][];
      page: components["schemas"]["EventQueryPage"];
      freshness: components["schemas"]["EventQueryFreshness"];
    };
    /** EventQueryFreshness */
    EventQueryFreshness: {
      /** Query Backend */
      query_backend: string;
      /** Canonical Store */
      canonical_store: string;
      /** Canonical Format */
      canonical_format: string;
      /**
       * Status
       * @default current
       */
      status: string;
      /** Detail */
      detail?: string | null;
      /** Watermark At */
      watermark_at?: string | null;
    };
    /** EventQueryPage */
    EventQueryPage: {
      /** Limit */
      limit: number;
      /** Returned */
      returned: number;
      /** Has More */
      has_more: boolean;
      /** Cursor */
      cursor?: string | null;
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** EvidenceBundleItem */
    EvidenceBundleItem: {
      pointer: components["schemas"]["EvidencePointer"];
      /** Raw Payload */
      raw_payload: {
        [key: string]: unknown;
      } | null;
      /** Retention Expired */
      retention_expired: boolean;
    };
    /** EvidencePointer */
    EvidencePointer: {
      /** Source */
      source: string;
      /** Object Key */
      object_key: string;
      /** Raw Event Id */
      raw_event_id: string;
      /** Observed At */
      observed_at: string;
    };
    /** FeatureTableStatus */
    FeatureTableStatus: {
      /** Action Row Count */
      action_row_count: number;
      /** History Row Count */
      history_row_count: number;
      /** Collaboration Row Count */
      collaboration_row_count: number;
      /** Static Row Count */
      static_row_count: number;
      /** Peer Group Row Count */
      peer_group_row_count: number;
    };
    /** FeatureVocabStatus */
    FeatureVocabStatus: {
      /** Principal Count */
      principal_count: number;
      /** Resource Count */
      resource_count: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /** IdentityProfilesStatus */
    IdentityProfilesStatus: {
      /** Available */
      available: boolean;
      /** Source */
      source?: string | null;
      /** Principal Count */
      principal_count: number;
      /** Team Count */
      team_count: number;
    };
    /** IntakeAccepted */
    IntakeAccepted: {
      /** Batch Id */
      batch_id: string;
      /** Tenant Id */
      tenant_id: string;
      /** Source */
      source: string;
      /** Integration Id */
      integration_id: string;
      /** Record Count */
      record_count: number;
      /** Manifest Key */
      manifest_key: string;
      /** Object Key */
      object_key: string;
      /** Idempotency Key */
      idempotency_key: string;
      /** Duplicate */
      duplicate: boolean;
      /** Queue Path */
      queue_path: string;
    };
    /** IntakeStatus */
    IntakeStatus: {
      /** Pending Batch Count */
      pending_batch_count: number;
      /** Processed Batch Count */
      processed_batch_count: number;
      /** Submitted Batch Count */
      submitted_batch_count: number;
      /** Accepted Idempotency Key Count */
      accepted_idempotency_key_count: number;
    };
    /** ModelActivationGateStatus */
    ModelActivationGateStatus: {
      /** Eligible */
      eligible: boolean;
      /** Reason */
      reason: string;
      /** Status */
      status?: string | null;
      /** Training Pair Count */
      training_pair_count: number;
      /** Final Loss */
      final_loss?: number | null;
      /** Evaluation Scope */
      evaluation_scope?: string | null;
      /** Sampled Top1 Accuracy */
      sampled_top1_accuracy?: number | null;
      /** Pairwise Win Rate */
      pairwise_win_rate?: number | null;
      /** Mean Margin */
      mean_margin?: number | null;
      /** Source Gates */
      source_gates?: {
        [key: string]: components["schemas"]["ModelSourceActivationGateStatus"];
      };
      /**
       * Evaluated Source Count
       * @default 0
       */
      evaluated_source_count: number;
      /** Failing Sources */
      failing_sources?: string[];
      coverage_gate?: components["schemas"]["ModelCoverageGateStatus"] | null;
    };
    /** ModelActivationRecord */
    ModelActivationRecord: {
      /** Action */
      action: string;
      /** Model Id */
      model_id?: string | null;
      /** Metadata Path */
      metadata_path?: string | null;
      /** Requested Mode */
      requested_mode: string;
      /** Activation Source */
      activation_source?: string | null;
      /** Activated At */
      activated_at?: string | null;
    };
    /** ModelCoverageGateStatus */
    ModelCoverageGateStatus: {
      /** Eligible */
      eligible: boolean;
      /** Reason */
      reason: string;
      /** Covered Sources */
      covered_sources?: string[];
      /** Covered Identity Sources */
      covered_identity_sources?: string[];
      /** Covered Resource Sources */
      covered_resource_sources?: string[];
      /**
       * Required Source Count
       * @default 0
       */
      required_source_count: number;
      /**
       * Require Identity Coverage
       * @default true
       */
      require_identity_coverage: boolean;
      /**
       * Require Resource Coverage
       * @default true
       */
      require_resource_coverage: boolean;
      /** Identity Sources */
      identity_sources?: string[];
      /** Resource Sources */
      resource_sources?: string[];
    };
    /** ModelPromotionPolicyStatus */
    ModelPromotionPolicyStatus: {
      /**
       * Required Source Count
       * @default 0
       */
      required_source_count: number;
      /**
       * Require Identity Coverage
       * @default true
       */
      require_identity_coverage: boolean;
      /**
       * Require Resource Coverage
       * @default true
       */
      require_resource_coverage: boolean;
      /** Identity Sources */
      identity_sources?: string[];
      /** Resource Sources */
      resource_sources?: string[];
    };
    /** ModelRuntimeStatus */
    ModelRuntimeStatus: {
      /** Available */
      available: boolean;
      /** Requested Mode */
      requested_mode: string;
      /** Effective Mode */
      effective_mode: string;
      /** Reason */
      reason: string;
      /** Model Id */
      model_id?: string | null;
      /** Model Version */
      model_version?: string | null;
      /** Model Family */
      model_family?: string | null;
      /** Exported At */
      exported_at?: string | null;
      /** Metadata Path */
      metadata_path?: string | null;
      /** Activated At */
      activated_at?: string | null;
      /** Activation Source */
      activation_source?: string | null;
      /** Action Source Count */
      action_source_count: number;
      /** Principal Vocab Count */
      principal_vocab_count: number;
      /** Resource Vocab Count */
      resource_vocab_count: number;
      activation_gate: components["schemas"]["ModelActivationGateStatus"];
      /** Recent Activation History */
      recent_activation_history: components["schemas"]["ModelActivationRecord"][];
      /** Installed Model Count */
      installed_model_count: number;
      /** Installed Model Ids */
      installed_model_ids: string[];
      score_policy?: components["schemas"]["ModelScorePolicyStatus"] | null;
      promotion_policy: components["schemas"]["ModelPromotionPolicyStatus"];
    };
    /** ModelScorePolicyStatus */
    ModelScorePolicyStatus: {
      /** Detection Threshold */
      detection_threshold: number;
      /** High Severity Threshold */
      high_severity_threshold: number;
      /** Calibration Source */
      calibration_source?: string | null;
      /** Calibration Reason */
      calibration_reason?: string | null;
      /** Positive Distance P95 */
      positive_distance_p95?: number | null;
      /** Negative Distance P50 */
      negative_distance_p50?: number | null;
      /** Negative Distance P90 */
      negative_distance_p90?: number | null;
      /** Evaluation Pair Count */
      evaluation_pair_count?: number | null;
      /** Source Policies */
      source_policies?: {
        [key: string]: components["schemas"]["ModelSourceScorePolicyStatus"];
      };
    };
    /** ModelSourceActivationGateStatus */
    ModelSourceActivationGateStatus: {
      /** Eligible */
      eligible: boolean;
      /** Reason */
      reason: string;
      /** Status */
      status?: string | null;
      /** Final Loss */
      final_loss?: number | null;
      /** Evaluation Scope */
      evaluation_scope?: string | null;
      /** Sampled Top1 Accuracy */
      sampled_top1_accuracy?: number | null;
      /** Pairwise Win Rate */
      pairwise_win_rate?: number | null;
      /** Mean Margin */
      mean_margin?: number | null;
      /** Pair Count */
      pair_count?: number | null;
    };
    /** ModelSourceScorePolicyStatus */
    ModelSourceScorePolicyStatus: {
      /** Detection Threshold */
      detection_threshold: number;
      /** High Severity Threshold */
      high_severity_threshold: number;
      /** Calibration Source */
      calibration_source?: string | null;
      /** Calibration Reason */
      calibration_reason?: string | null;
      /** Positive Distance P95 */
      positive_distance_p95?: number | null;
      /** Negative Distance P50 */
      negative_distance_p50?: number | null;
      /** Negative Distance P90 */
      negative_distance_p90?: number | null;
      /** Evaluation Pair Count */
      evaluation_pair_count?: number | null;
    };
    /** OpsMetadata */
    OpsMetadata: {
      /** Workspace */
      workspace?: string | null;
      /** Event Counts By Source */
      event_counts_by_source: {
        [key: string]: number;
      };
      /** Dead Letter Count */
      dead_letter_count: number;
      /** Dead Letter Counts By Source */
      dead_letter_counts_by_source?: {
        [key: string]: number;
      } | null;
      /** Contains Raw Payloads */
      contains_raw_payloads?: boolean | null;
    };
    /** Overview */
    Overview: {
      stream_state: components["schemas"]["StreamState"];
      ops_metadata: components["schemas"]["OpsMetadata"];
    };
    /** Pagination */
    Pagination: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Returned */
      returned: number;
      /** Total */
      total?: number | null;
      /** Has More */
      has_more: boolean;
    };
    /** PostgresStatus */
    PostgresStatus: {
      /** Root */
      root: string;
      /** Dsn */
      dsn?: string | null;
      /** Paths */
      paths: {
        [key: string]: string;
      };
      /** Initialized */
      initialized: boolean;
    };
    /** Principal */
    Principal: {
      /** Id */
      id: string;
      /** Entity Id */
      entity_id: string;
      /** Entity Key */
      entity_key: string;
      /** Kind */
      kind: string;
      /** Provider */
      provider: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Department */
      department: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
    };
    /** QuickwitStatus */
    QuickwitStatus: {
      /** Root */
      root: string;
      /** Url */
      url: string;
      /** Index Id */
      index_id: string;
      /** Config Path */
      config_path: string;
      /** Log Path */
      log_path: string;
      /** Paths */
      paths: {
        [key: string]: string;
      };
      /** Initialized */
      initialized: boolean;
      /** Pid */
      pid?: number | null;
      /** Running */
      running: boolean;
      /** Ready */
      ready: boolean;
      /** Rss Bytes */
      rss_bytes?: number | null;
      /** Log Size Bytes */
      log_size_bytes: number;
      /** Last Start Attempted At */
      last_start_attempted_at?: string | null;
      /** Last Start Completed At */
      last_start_completed_at?: string | null;
      /** Last Start Duration Ms */
      last_start_duration_ms?: number | null;
      /** Last Start Status */
      last_start_status?: string | null;
      /** Last Start Error */
      last_start_error?: string | null;
      /** Watermark At */
      watermark_at?: string | null;
      /** Indexed Event Count */
      indexed_event_count: number;
      /** Last Sync Completed At */
      last_sync_completed_at?: string | null;
      /** Last Sync Duration Ms */
      last_sync_duration_ms?: number | null;
      /** Last Sync Status */
      last_sync_status?: string | null;
      /** Last Sync Error */
      last_sync_error?: string | null;
    };
    /** Resource */
    Resource: {
      /** Id */
      id: string;
      /** Entity Id */
      entity_id: string;
      /** Entity Key */
      entity_key: string;
      /** Kind */
      kind: string;
      /** Provider */
      provider: string;
      /** Name */
      name: string;
      /** Sensitivity */
      sensitivity: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
    };
    /** RuntimeStatus */
    RuntimeStatus: {
      /** Workspace */
      workspace: string;
      /** Tenant Id */
      tenant_id: string;
      stream_state: components["schemas"]["StreamState"];
      worker_state: components["schemas"]["WorkerState"];
      feature_tables: components["schemas"]["FeatureTableStatus"];
      feature_vocab: components["schemas"]["FeatureVocabStatus"];
      scoring_input: components["schemas"]["ScoringInputStatus"];
      model_runtime: components["schemas"]["ModelRuntimeStatus"];
      event_index: components["schemas"]["EventIndexStatus"];
      canonical_event_store: components["schemas"]["CanonicalEventStoreStatus"];
      quickwit: components["schemas"]["QuickwitStatus"];
      detection_context: components["schemas"]["DetectionContextStatus"];
      identity_profiles: components["schemas"]["IdentityProfilesStatus"];
      worker_control: components["schemas"]["WorkerControlStatus"];
      intake: components["schemas"]["IntakeStatus"];
      postgres: components["schemas"]["PostgresStatus"];
    };
    /** ScoringInputStatus */
    ScoringInputStatus: {
      /** Ready */
      ready: boolean;
      /** Mode */
      mode: string;
      /** Reason */
      reason: string;
      /** Materialized Table Count */
      materialized_table_count: number;
      /** Materialized Tables */
      materialized_tables: string[];
    };
    /** SourceCapabilityDetails */
    SourceCapabilityDetails: {
      /** Display Name */
      display_name: string;
      /** Required Event Types */
      required_event_types: string[];
      /** Required Fields */
      required_fields: string[];
      /** Seen Event Types */
      seen_event_types: string[];
      /** Missing Required Event Types */
      missing_required_event_types: string[];
      /** Required Field Coverage */
      required_field_coverage: {
        [key: string]: boolean;
      };
      /** Missing Required Fields */
      missing_required_fields: string[];
      /** Recent Window Anchor At */
      recent_window_anchor_at?: string | null;
      /** Raw Last Seen At */
      raw_last_seen_at?: string | null;
      /** Normalized Last Seen At */
      normalized_last_seen_at?: string | null;
      /** Raw 24H Count */
      raw_24h_count: number;
      /** Normalized 24H Count */
      normalized_24h_count: number;
      /** Dead Letter 7D Count */
      dead_letter_7d_count: number;
      /** Raw Event Count */
      raw_event_count: number;
      /** Normalized Event Count */
      normalized_event_count: number;
      /** Dead Letter Count */
      dead_letter_count: number;
      /** Dead Letter Reason Counts */
      dead_letter_reason_counts: {
        [key: string]: number;
      };
    };
    /** SourceCapabilityMatrix */
    SourceCapabilityMatrix: {
      /** Source Pack */
      source_pack: string[];
      /** Sources */
      sources: {
        [key: string]: components["schemas"]["SourceCapabilityDetails"];
      };
    };
    /** StreamAdvance */
    StreamAdvance: {
      /** Status */
      status: string;
      /** Cursor */
      cursor: number;
      /** Total Source Events */
      total_source_events: number;
      /** Complete */
      complete: boolean;
      /** Batch Size */
      batch_size: number;
      /** Accepted Batches */
      accepted_batches: number;
      /** Accepted Records */
      accepted_records: number;
      /** Pending Batch Count */
      pending_batch_count: number;
    };
    /** StreamReset */
    StreamReset: {
      /** Status */
      status: string;
      /** Total Source Events */
      total_source_events: number;
      /** Cursor */
      cursor: number;
    };
    /** StreamState */
    StreamState: {
      /** Cursor */
      cursor: number;
      /** Total Source Events */
      total_source_events: number;
      /** Complete */
      complete: boolean;
      /** Normalized Event Count */
      normalized_event_count?: number | null;
      /** Detection Count */
      detection_count?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorkerControlStatus */
    WorkerControlStatus: {
      /** Source Stats Refresh Requested */
      source_stats_refresh_requested: boolean;
      /** Source Stats Refresh Requested At */
      source_stats_refresh_requested_at?: string | null;
    };
    /** WorkerState */
    WorkerState: {
      /** Normalization Runs */
      normalization_runs: number;
      /** Feature Runs */
      feature_runs: number;
      /** Detection Runs */
      detection_runs: number;
      /** Source Stats Runs */
      source_stats_runs: number;
      /** Service Runs */
      service_runs: number;
      /** Last Submitted Batch Id */
      last_submitted_batch_id?: string | null;
      /** Last Processed Batch Id */
      last_processed_batch_id?: string | null;
      /** Last Normalization At */
      last_normalization_at?: string | null;
      /** Last Feature At */
      last_feature_at?: string | null;
      /** Last Detection At */
      last_detection_at?: string | null;
      /** Last Source Stats At */
      last_source_stats_at?: string | null;
      /** Last Service At */
      last_service_at?: string | null;
      /** Last Service Status */
      last_service_status?: string | null;
      /** Pending Batch Count */
      pending_batch_count: number;
      /** Processed Batch Count */
      processed_batch_count: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  intake_raw_events_api_intake_raw_events_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IntakeAccepted"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  worker_state_api_workers_state_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkerState"];
        };
      };
    };
  };
  runtime_status_api_runtime_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuntimeStatus"];
        };
      };
    };
  };
  stream_reset_api_stream_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamReset"];
        };
      };
    };
  };
  stream_advance_api_stream_advance_post: {
    parameters: {
      query?: {
        batch_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamAdvance"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_state_api_stream_state_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StreamState"];
        };
      };
    };
  };
  overview_api_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Overview"];
        };
      };
    };
  };
  events_api_events_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
        start_time?: string | null;
        end_time?: string | null;
        query?: string | null;
        sources?: string[] | null;
        action_categories?: string[] | null;
        sensitivities?: string[] | null;
        principal_reference?: string | null;
        resource_reference?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detections_api_detections_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectionList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detection_detail_api_detections__detection_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        detection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectionDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  entity_detail_api_entities__principal_key__get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        principal_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detection_acknowledge_api_detections__detection_id__acknowledge_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        detection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detection"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  source_capability_api_source_capability_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceCapabilityMatrix"];
        };
      };
    };
  };
  event_detail_api_events__event_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Event"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
